# Generated by Django 3.1.7 on 2021-04-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=122)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
