# Generated by Django 3.1.7 on 2021-04-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210419_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registrationID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateField(),
        ),
    ]
