# Generated by Django 3.1.7 on 2021-04-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210419_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registrationID',
            new_name='registrationNumber',
        ),
    ]
