# Generated by Django 3.1.7 on 2021-04-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20210419_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
