# Generated by Django 3.1.7 on 2021-04-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('status', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=122)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
