# Generated by Django 3.1.7 on 2021-04-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
